### ISSUE TITLE
键盘不弹出

### ISSUE THREAD

**Issue by Monkeyzc** [chernyog/CYPasswordView#1]
验证指纹成功后, 调用 showInView, 在iOS10上不能够弹出键盘, 升级iOS 10.1 就没有这个问题了, 如果你有在不需要更新系统的情况可以解决这个问题, 请告诉我, 谢谢

**Comment by chernyog** [comment]
谢谢反馈，等我几天升级Xcode后再看看这个问题。

**Comment by Monkeyzc** [comment]
键盘的弹出貌似会跟验证指纹的弹框会冲突, 可以延时0.5s在弹出, 就可以解决问题了
