### ISSUE TITLE
是否可以支持 Swift ?

### ISSUE THREAD

**Issue by trusbe** [chernyog/CYPasswordView#6]
是否继续推出 Swift 版本？

**Comment by chernyog** [comment]
你好，会推出Swift版本，正在抽空完成。

**Comment by chernyog** [comment]
你好，Swift版本已完成，有问题请反馈。https://github.com/chernyog/PasswordView

**Comment by chernyog** [comment]
> 是否继续推出 Swift 版本？

你好，Swift版本已完成，有问题请反馈。https://github.com/chernyog/PasswordView

**Comment by trusbe** [comment]
@chernyog  🐂🍺，感谢
